version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: odoo17-db
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

  odoo:
    image: odoo:17.0
    container_name: odoo17-app
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      # Mapeia o arquivo de configuração
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      # Mapeia a pasta de addons customizados (CORRIGIDO)
      - ./custom_addons:/mnt/extra-addons
    restart: unless-stopped
    # ADICIONADO: Comando para instalar módulos automaticamente
    command: -- -i sale_management,sale_whatsapp_integration -d odoo17-teste --stop-after-init